fox0430/moe

- myEdiotr.c
> fix insertChar

- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
> Fix travis error

- src/moepkg/filermode.nim
> filermode: bugfix #102

- src/moepkg/normalmode.nim
Changed to save to a register when deleting a lines.
> Improve yank line

- src/moepkg/editorstatus.nim
- src/moepkg/normalmode.nim
Add yank string and add 'P' command in normal mode.
> normalmode: Add yank string and 'P' command

- src/moepkg/editorstatus.nim
> Fix column number in status bar

- src/moepkg/normalmode.nim
> Insertmode: Bugfix #120

- src/moe.nim
- src/moepkg/editorstatus.nim
- src/moepkg/editorview.nim
- src/moepkg/highlight.nim
- src/moepkg/insertmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/settings.nim
- src/moepkg/ui.nim
- src/moepkg/unicodeext.nim
- tests/teditorstatus.nim
> Syntax highlighting

- src/moepkg/filermode.nim
Refactoring
Add copy and move file command
Add create directory command
Various sorts
> Improve filer

- src/moepkg/filermode.nim
> Filer mode: Bug fix #129

- src/moepkg/exmode.nim
> Ex mode: Bugfix #133

- src/moepkg/fileutils.nim
> Ex mode: Bugfix #135

- moe.nimble
- src/moepkg/ui.nim
And I fixed some type conversions in ui.nim.
However this fix is foolishly honest, so I have no confidence ... .
> Fix #138:   Use my forked nim-ncurses repository instead of origin temporarily

- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
> Add ex mode display to status bar

- src/moepkg/normalmode.nim
> Normal mode: Add 'e' command

- src/moe.nim
- src/moepkg/editorstatus.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
> Add replace mode

- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/ui.nim
> Support cursor movement in EX mode

- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/highlight.nim
- src/moepkg/insertmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/searchmode.nim
- src/moepkg/ui.nim
Use `editorstatus.updateHighlight` instead of `highlight.initHighlight`.
(Note: I chose magenta as default highlighting color.)
Close #159
> Add search result highlighting

- src/moepkg/replacemode.nim
> Bug fix replace mode

- src/moe.nim
- src/moepkg/editorstatus.nim
- src/moepkg/highlight.nim
- src/moepkg/normalmode.nim
- src/moepkg/visualmode.nim
> Add visual mode

- src/moepkg/highlight.nim
- src/moepkg/insertmode.nim
And fixed `insertMode`.
Close #185
> Make it possible to highlight files starting with newlines

- src/moe.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/mainview.nim
> Support multiple file buffers

- src/moepkg/exmode.nim
> Support change setting in ex mode

- README.md
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/settings.nim
- src/moepkg/tab.nim
> IDE Like tab line

- example/moerc.toml
- src/moe.nim
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/editorview.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/highlight.nim
- src/moepkg/settings.nim
- src/moepkg/tab.nim
- src/moepkg/ui.nim
- tests/teditorstatus.nim
Close #215 
Support vivid, dark and light theme
> Support color theme

- src/moe.nim
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/editorview.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/insertmode.nim
- src/moepkg/mainview.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/searchmode.nim
- src/moepkg/tab.nim
- src/moepkg/visualmode.nim
- tests/teditorstatus.nim
> Support split window

- src/moepkg/exmode.nim
> Ex mode: Fix #232

- src/moepkg/commandview.nim
- src/moepkg/editorview.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
Add some commands  #253 
```ZZ```, ```ZQ```, ```z.```, ```zb```,  ```zt```
> Add command

- src/moepkg/editorstatus.nim
- src/moepkg/editorview.nim
- src/moepkg/ui.nim
> Support cursor line

- src/moe.nim
- src/moepkg/buffermanager.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
> Support buffer manager

- src/moepkg/filermode.nim
> Improvement of file detail

- src/moepkg/normalmode.nim
> Normal mode: Fix #295

- src/moepkg/normalmode.nim
> Normal mode: Add dw command

- src/moe.nim
- src/moepkg/editorstatus.nim
- src/moepkg/normalmode.nim
- src/moepkg/ui.nim
- src/moepkg/visualmode.nim
> Support visual block mode

- src/moepkg/visualmode.nim
> Visual mode: Add 'r' command

- example/moerc.toml
> Update configuration example

- src/moepkg/ui.nim
> Disable new line mode of ncurses and fix isEnterKey()

- src/moepkg/editorstatus.nim
> Fixed language not set when opening a new file

- example/moerc.toml
- src/moe.nim
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/fileutils.nim
- src/moepkg/insertmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/settings.nim
- src/moepkg/visualmode.nim
> Support auto save

- example/moerc.toml
- src/moe.nim
- src/moepkg/editorstatus.nim
- src/moepkg/insertmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/settings.nim
- src/moepkg/visualmode.nim
> Add support live reload of configuration file

- src/moepkg/normalmode.nim
> Add "d$" and "d0" command in normal mode

- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
> Ex mode: Add error message (#358)

- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
> Ex mode: Add file saved message (#361)

- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
> Erase the characters entered when exiting ex mode

- src/moepkg/normalmode.nim
> Normal mode: Add yw command

- src/moepkg/insertmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/ui.nim
- src/moepkg/visualmode.nim
> Supports Ctrl-[ and f command

- src/moepkg/editorstatus.nim
- src/moepkg/ui.nim
> Change syntax highlighting color to match editor color theme

- README.md
- src/moepkg/commandview.nim
- src/moepkg/ui.nim
- src/moepkg/unicodeext.nim
> Ex mode: Support suggest

- README.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/searchmode.nim
- src/moepkg/settings.nim
> Exmode: Support real time search

- .gitignore
- src/moe.nim
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/logviewer.nim
- src/moepkg/normalmode.nim
> Support messages log viewer

- src/moepkg/editorstatus.nim
- src/moepkg/normalmode.nim
- src/moepkg/unicodeext.nim
- src/moepkg/visualmode.nim
> Support clip board

- src/moepkg/normalmode.nim
> Clipboard: Fix implementation

- example/moerc.toml
- src/moepkg/editorstatus.nim
- src/moepkg/settings.nim
> Support display all buffers in tab line

- documents/configfile.md
- example/moerc.toml
- src/moepkg/editorstatus.nim
- src/moepkg/settings.nim
- src/moepkg/tree.nim
- src/moepkg/ui.nim
> Support change status bar color when change mode

- src/moepkg/commandview.nim
- src/moepkg/ui.nim
Close #411 
Support shift + tab  
Fixed an issue where matching commands were not suggested afterwards  
Fixed an issue where file path was not suggested correctly
> Ex mode: Fix and improve suggestion

- documents/configfile.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/settings.nim
- src/moepkg/ui.nim
> Support pop up window, Supports pop-up window with ex mode suggestions

- README.md
- documents/configfile.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/searchmode.nim
- src/moepkg/settings.nim
- src/moepkg/ui.nim
> Support highlighting when replace text

- src/moe.nim
- src/moepkg/ui.nim
> Allow to interrupt the opening of a file with Ctrl-c (#466)

- documents/configfile.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/settings.nim
- src/moepkg/ui.nim
- src/moepkg/unicodeext.nim
- tests/teditorstatus.nim
- tests/texmode.nim
> Highlight a pair of paren (#469)

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/insertmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/settings.nim
- tests/teditorstatus.nim
- tests/texmode.nim
- tests/tnormalmode.nim
> Auto delete paren

- documents/configfile.md
- documents/howtouse.md
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/settings.nim
- src/moepkg/ui.nim
- tests/texmode.nim
> Suuport smooth scroll

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/settings.nim
- src/moepkg/visualmode.nim
- tests/texmode.nim
> Add clipboard setting

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/editorview.nim
- src/moepkg/exmode.nim
- src/moepkg/highlight.nim
- src/moepkg/settings.nim
- src/moepkg/ui.nim
- src/moepkg/visualmode.nim
- tests/teditorstatus.nim
- tests/texmode.nim
- tests/tvisualmode.nim
> Support highlighting other uses of the current word under the cursor

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/settings.nim
- src/moepkg/ui.nim
- tests/teditorstatus.nim
- tests/texmode.nim
> Support Highlight full-width space

- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
> Ex mode: Fix file path suggestions

- src/moe.nim
- src/moepkg/cmdlineoption.nim
> Open multiple files from the command line

- src/moepkg/normalmode.nim
- src/moepkg/visualmode.nim
- tests/tvisualmode.nim
> Fix clipboard in visual (block) mode

- tests/teditorstatus.nim
> Add unit tests of split and close window

- documents/overview.md
> Document: Improve installation

- example/moerc.toml
- src/moe.nim
- src/moepkg/buffermanager.nim
- src/moepkg/color.nim
- src/moepkg/commandview.nim
- src/moepkg/editor.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/insertmode.nim
- src/moepkg/logviewer.nim
- src/moepkg/movement.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/searchmode.nim
- src/moepkg/settings.nim
- src/moepkg/visualmode.nim
- src/moepkg/workspace.nim
- tests/teditorstatus.nim
- tests/texmode.nim
- tests/tinsertmode.nim
- tests/tlogviewer.nim
- tests/tnormalmode.nim
- tests/tvisualmode.nim
> Support workspace

- src/moepkg/normalmode.nim
- tests/tnormalmode.nim
> Rewrite normal mode unit tests (#600)

- tests/tworkspace.nim
> Add work space unit tests (#601)

- src/moepkg/color.nim
- src/moepkg/highlight.nim
- tests/thighlight_private.nim
Add highlighting TODO and WIP.
I will remove `WIP` if you don't need WIP.
(WIP is a word for my test code)
> Highlights "TODO" in comments #461

- src/moepkg/highlight.nim
- tests/thighlight_private.nim
> Highlights "NOTE" in comments (#616)

- src/moepkg/editorstatus.nim
- src/moepkg/logviewer.nim
- tests/tlogviewer.nim
> Real-time update of log viewer

- documents/howtouse.md
- src/moe.nim
- src/moepkg/bufferstatus.nim
- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
- src/moepkg/help.nim
- src/moepkg/helpsentence.nim
- tests/texmode.nim
- tests/thelp.nim
> Add Help support (#209)

- src/moepkg/insertmode.nim
- src/moepkg/movement.nim
- src/moepkg/normalmode.nim
Another one of my favorite vim movements.
Here I used my own experimental code formatting style,
please feel free to change all or any part of it.
Oh, and I also added _ for navigating to the first non-blank character in the current line,
which is an alias for ^, that is hard to type on some keyboards.
And I added g_ which moves to the last non-blank character in the current line,
which is different from $ that moves to the last character whatever it may be.
> Implemented ctrl+u vim movement for insert mode.

- src/moepkg/editor.nim
- src/moepkg/movement.nim
- src/moepkg/normalmode.nim
Also added _ as alias for ^, which I apparently forgot to stage
for the last commit,
small reordering of code in normalmode.nim by using templates.
Please note, that D and S operations so far don't yank
anything, I noticed that existing operations such
as d$ and d0 don't do it yet either, so we have to add
this functionality for all of them.
> Added vim D as alias for existing d$, new operation S (and an alias cc)

- src/moepkg/statusbar.nim
Uses ~ for shortening. Saves spaces and looks better.
> Shorten filename in statusBar, if it is in home

- src/moepkg/filermode.nim
> Added icons to filer mode using unicode symbols.

- src/moepkg/filermode.nim
As discussed in #653.
This always keeps the list of directories before the list of files.
The sorting still works, but it keeps dirs and files separated.
Hopefully I didn't misunderstand you, maybe you don't like
the idea.
> Keep directories before files. Discussed in #653

- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
I forgot to add this with the initial implementation.
> Indentation lines live setting

- src/moepkg/insertmode.nim
Makes ctrl+u behave like intended in insert mode.
> Fix. Forgot to add this line to commit 4c0c9676.

- src/moepkg/normalmode.nim
this is only preliminary support. I think the searches aren't being added to the search history right now,
it doesn't bother me, though.
This also contains a fix, that should make the ctrl+a/ctrl+x thing more reliable.
> searching forward/reverse with # and *. WIP.

- src/moepkg/editorview.nim
> Activate indentation lines by default

- documents/configfile.md
- example/moerc.toml
- src/moepkg/color.nim
- src/moepkg/editorstatus.nim
- src/moepkg/settings.nim
- tests/teditorstatus.nim
> Add support for highlight trailing spaces (#643)

- src/moepkg/ui.nim
> Blinking i-beam cursor (#647)

- src/moepkg/editorstatus.nim
- src/moepkg/tabline.nim
> Improve workspace line

- documents/configfile.md
- example/moerc.toml
- src/moepkg/color.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/highlight.nim
- src/moepkg/settings.nim
- tests/teditorstatus.nim
- tests/thighlight.nim
- tests/thighlight_private.nim
- tests/tinsertmode.nim
- tests/tmovement.nim
- tests/tvisualmode.nim
> Highlighting any word (#632)

- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/unicodeext.nim
> Ex mode: Fix popup window position (#737) and improve performance

- src/moepkg/editorstatus.nim
- tests/teditorstatus.nim
> Don't highlight the word at current cursor position (#743)

- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- tests/tnormalmode.nim
> Normal mode: Add '.' command (Repeat last command) (#732)

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
- src/moepkg/settings.nim
- src/moepkg/statusbar.nim
- tests/texmode.nim
Show/Hide git branch name in status bar when in inactive window
> Add statusBar.showGitInactive setting and 'showGitInactive' ex command

- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
> Ex mode: Ask create a dir if does not exist when save/write file (#750)

- src/moepkg/movement.nim
- tests/tinsertmode.nim
> Insert mode: Fix move to last of current line (#757)

- src/moepkg/exmode.nim
> Fix file save (#779)

- src/moepkg/visualmode.nim
> Fix crash when delete buffer in visual mode (#794)

- src/moepkg/editorstatus.nim
- tests/teditorstatus.nim
> Don't highlight whitespaces at end of line in current line (#793)

- src/moepkg/window.nim
> Fix window position after vertical split window (#800)

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
- src/moepkg/settings.nim
- tests/texmode.nim
> Quick run support (#784)

- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
> Quick run: Add supports for sh and bash

- documents/howtouse.md
- src/moe.nim
- src/moepkg/bufferstatus.nim
- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
- src/moepkg/recentfilemode.nim
- src/moepkg/statusbar.nim
> Recent file selection (#760)

- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
> Ex mode: Command case insensitive (#778)

- README.md
- documents/configfile.md
- example/moerc.toml
- src/moe.nim
- src/moepkg/backup.nim
- src/moepkg/buffermanager.nim
- src/moepkg/commandview.nim
- src/moepkg/editor.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/help.nim
- src/moepkg/insertmode.nim
- src/moepkg/logviewer.nim
- src/moepkg/messages.nim
- src/moepkg/normalmode.nim
- src/moepkg/recentfilemode.nim
- src/moepkg/replacemode.nim
- src/moepkg/settings.nim
- src/moepkg/unicodeext.nim
- src/moepkg/visualmode.nim
- tests/tbackup.nim
> Add support for automatic backups (#762)

- src/moepkg/exmode.nim
- src/moepkg/messages.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
> Display message while running quickrun (#820)

- src/moe.nim
- src/moepkg/bufferstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
- src/moepkg/statusbar.nim
> Quick run: Do not open window when already opened quickrun window (#823)

- documents/configfile.md
- example/moerc.toml
- src/moepkg/editorstatus.nim
- src/moepkg/insertmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/settings.nim
> Add setting to disable the change of the cursor shape

- documents/configfile.md
- example/moerc.toml
- src/moepkg/messages.nim
- src/moepkg/quickrun.nim
- src/moepkg/settings.nim
> Quick run: Add timeout setting to Quickrun

- src/moepkg/backup.nim
- src/moepkg/buffermanager.nim
- src/moepkg/bufferstatus.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/help.nim
- src/moepkg/insertmode.nim
- src/moepkg/logviewer.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
- src/moepkg/statusbar.nim
- src/moepkg/tabline.nim
- tests/teditorstatus.nim
- tests/texmode.nim
- tests/thelp.nim
> Rename BufferStatus.filename to BufferStatus.path (#819)

- .gitignore
- src/moepkg/color.nim
- src/moepkg/ui.nim
- tests/config.nims
> Not write UI when running unit tests

- src/moepkg/normalmode.nim
And I removed some spaces in empty lines
> Move to a line with gg (like vim)

- src/moepkg/highlight.nim
- src/moepkg/highlite.nim
> Add support for JavaScript syntax highlighting (#320)

- src/moepkg/statusbar.nim
> Fix git branch name color in status bar (#856)

- src/moepkg/exmode.nim
> Change mode label in statusbar when putting ':'

- src/moepkg/settings.nim
> Fix Standard.popUpWindowInExmode (#860)

- src/moepkg/settings.nim
> Fix StatusBar.filename (#862)

- src/moe.nim
- src/moepkg/editorstatus.nim
- src/moepkg/settings.nim
- tests/tsettings.nim
> Add unit tests for configuration file (#786)

- src/moepkg/filermode.nim
Fixed the problem that targets of symbolic links are not displayed in filer mode.
> Fix filermode.fileNameToGapBuffer

- documents/howtouse.md
- src/moepkg/visualmode.nim
> Visual block mode: Add Shift+i command (Insert character multile line… 

- src/moepkg/visualmode.nim
- tests/tvisualmode.nim
> Visual block mode: Fix #885

- src/moepkg/visualmode.nim
- tests/tvisualmode.nim
> Visual mode: Fix #890

- src/moepkg/filermode.nim
> Avoid getFileSize if the file is a named pipe

- src/moepkg/exmode.nim
> QuickRun: Fix #899

- src/moepkg/logviewer.nim
> Log viewer: Fix #908

- src/moepkg/exmode.nim
- tests/texmode.nim
> Ex mode: Fix sp command (#904)

- documents/configfile.md
- example/moerc.toml
- src/moepkg/quickrun.nim
- src/moepkg/settings.nim
- tests/tsettings.nim
> QuickRun: Add QuickRun.saveBufferWhenQuickRun setting

- src/moepkg/quickrun.nim
> Quick Run: Showing the output even if QuickRun faile (#916)

- src/moepkg/editorstatus.nim
- src/moepkg/messages.nim
> Show error message if select not exist workspace (#918)

- documents/howtouse.md
- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
- src/moepkg/messages.nim
- tests/texmode.nim
> Ex mode: Add lsw command (Show all workspace) (#919)

- documents/configfile.md
- example/moerc.toml
- src/moe.nim
- src/moepkg/backup.nim
- src/moepkg/editor.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/messages.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
- src/moepkg/settings.nim
- tests/tsettings.nim
> Add Notification settings (#911) and Delete AutoBackup.showMessages

- documents/howtouse.md
- src/moepkg/editor.nim
- src/moepkg/editorstatus.nim
- src/moepkg/movement.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- tests/treplacemode.nim
> Fix replace mode behavior

- src/moepkg/commandview.nim
- src/moepkg/fileutils.nim
> Ex mode: Enable '~' (Home dir) in e command (#955)

- src/moepkg/highlight.nim
- src/moepkg/highlite.nim
- src/moepkg/quickrun.nim
Show "Shell" on status bar if open .sh or .bash file
> improve shell script support and refactor quickrun.nim

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moe.nim
- src/moepkg/bufferstatus.nim
- src/moepkg/color.nim
- src/moepkg/commandview.nim
- src/moepkg/diffviewer.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/historymanager.nim
- src/moepkg/messages.nim
- src/moepkg/settings.nim
- src/moepkg/statusbar.nim
- src/moepkg/tabline.nim
- tests/thistorymanager.nim
- tests/tsettings.nim
Experimental features
Add History mode (Backup history manager)
Add ```history``` command in ex mode (Open backup history manager)
Add Diff mode (diff viewer for backup files)
Link #762
> Add history mode (Backup history) and diff mode

- src/moepkg/editor.nim
- src/moepkg/insertmode.nim
- tests/teditor.nim
- tests/teditorstatus.nim
- tests/tinsertmode.nim
> Tabs erasing #837

- src/moepkg/color.nim
> Fix Theme.editorBg setting (#976)

- src/moepkg/bufferstatus.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/historymanager.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
- src/moepkg/settings.nim
- src/moepkg/statusbar.nim
EditorSettings.characterEncoding move to BufferStatus
> EditorSettings.characterEncoding move to BufferStatus

- documents/configfile.md
- documents/howtouse.md
- example/moerc.toml
- src/moepkg/configmode.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/search.nim
- src/moepkg/settings.nim
- tests/texmode.nim
- tests/tsearch.nim
- tests/tsettings.nim
> Add settings for searching

- src/moe.nim
- src/moepkg/backup.nim
- src/moepkg/build.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/historymanager.nim
- src/moepkg/insertmode.nim
- src/moepkg/recentfilemode.nim
- src/moepkg/settings.nim
- Fix Deprecation Warnings.
:)
> Fix Deprecations

- src/moepkg/color.nim
- src/moepkg/editorstatus.nim
- src/moepkg/ui.nim
Convert color 256 to 8 colors if moe running on consoles.
Close #752
> Improved color support on Linux consoles

- example/moerc.toml
- tests/tsettings.nim
> Fix configuration file example and added unit test

- src/moepkg/commandview.nim
> Ex mode: Fix "sv" command

- src/moepkg/bufferstatus.nim
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
> Add warn message

- src/moepkg/backup.nim
- src/moepkg/buffermanager.nim
- src/moepkg/commandline.nim
- src/moepkg/commandview.nim
- src/moepkg/configmode.nim
- src/moepkg/diffviewer.nim
- src/moepkg/editor.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/help.nim
- src/moepkg/historymanager.nim
- src/moepkg/insertmode.nim
- src/moepkg/logviewer.nim
- src/moepkg/messages.nim
- src/moepkg/normalmode.nim
- src/moepkg/quickrun.nim
- src/moepkg/recentfilemode.nim
- src/moepkg/replacemode.nim
- src/moepkg/search.nim
- src/moepkg/visualmode.nim
Keep command line buffer even if resize the window
> Fix commandline view

- documents/howtouse.md
- src/moepkg/exmode.nim
> Ex mode: Add "w!" command (Force write) (#846)

- src/moepkg/exmode.nim
- tests/texmode.nim
Link https://github.com/fox0430/moe/commit/d6448c63e3211a31030f6833bbb6443c85302a41#r42819728
> Fix w! command (Force write)

- documents/howtouse.md
- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
- tests/texmode.nim
> Ex mode: Add wq! command (Force write and quit)

- src/moepkg/editorstatus.nim
> Ex mode: Fix #1074

- documents/configfile.md
- example/moerc.toml
- src/moepkg/configmode.nim
- src/moepkg/editorstatus.nim
- src/moepkg/settings.nim
- tests/tsettings.nim
> Fix typo (#1088)

- src/moepkg/visualmode.nim
- tests/tvisualmode.nim
> Fix #1123 and #1124

- .github/workflows/actions.yaml
- src/moepkg/buffermanager.nim
- src/moepkg/commandview.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/filermode.nim
- src/moepkg/insertmode.nim
- src/moepkg/logviewer.nim
- src/moepkg/normalmode.nim
- src/moepkg/suggestionwindow.nim
- tests/teditorstatus.nim
- tests/texmode.nim
- tests/tfilermode.nim
- tests/tinsertmode.nim
- tests/tlogviewer.nim
- tests/tnormalmode.nim
- tests/tquittest1.nim
- tests/tquittest2.nim
- tests/tquittest3.nim
- tests/tquittest4.nim
- tests/tquittest5.nim
> Add GitHub Actions workflow

- src/moepkg/editor.nim
- tests/config.nims
- tests/tinsertmode.nim
> Insert mode: Fix add/delete indent behavior

- README.md
- src/moepkg/editor.nim
- src/moepkg/movement.nim
- src/moepkg/normalmode.nim
I've also added deletion with those movements.
I tried to follow your coding style as close as possible. If you have questions please let me know.
> Added { and } movements.

- src/moepkg/highlight.nim
- tests/thighlight.nim
> Fix #1166 and add unit test

- documents/howtouse.md
- src/moepkg/normalmode.nim
- tests/tnormalmode.nim
> Normal mode: Add s and cl commands

- src/moepkg/normalmode.nim
- tests/tnormalmode.nim
> Normal mode: Fix #1209 and cl command

- .github/workflows/actions.yaml
> CI: Add build on Nim devel

- src/moepkg/configmode.nim
- tests/tconfigmode.nim
> Configuration mode: Add support for change string settings (#1225)

- src/moepkg/commandline.nim
- src/moepkg/commandview.nim
- src/moepkg/ui.nim
> Exit Ex mode with Ctrl-C (#373)

- src/moepkg/generalautocomplete.nim
- src/moepkg/insertmode.nim
- src/moepkg/suggestionwindow.nim
- tests/tinsertmode.nim
> Autocomplete words in buffers of other windows (#1244)

- documents/developer.md
- documents/index.md
> Add developer documentation (#1251)

- src/moepkg/editorstatus.nim
> Highlighting search result and trailing spaces in all windows (#1258)

- src/moepkg/bufferstatus.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/search.nim
> Search text in all windows (#1260)

- src/moepkg/commandview.nim
- src/moepkg/exmode.nim
- tests/tcommandview.nim
> Ex mode: Add "build" command (build the current buffer)

- documents/configfile.md
- example/moerc.toml
- src/moe.nim
- src/moepkg/buffermanager.nim
- src/moepkg/configmode.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/settings.nim
- tests/tconfigmode.nim
- tests/tsettings.nim
> Persists Ex command history and search history (#877)

- documents/configfile.md
- example/moerc.toml
- src/moepkg/editorstatus.nim
- src/moepkg/settings.nim
- tests/tconfigmode.nim
- tests/tsettings.nim
> Fix #1281 and Enable Persist settings by default

- src/moepkg/bufferstatus.nim
- src/moepkg/configmode.nim
- src/moepkg/editor.nim
- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/search.nim
- src/moepkg/visualmode.nim
- tests/teditorstatus.nim
- tests/thelp.nim
An editor view updates faster about 5x in a release build.
Close #1076
> Improve the performance of highlight updates (#1076)

- src/moepkg/editorstatus.nim
- src/moepkg/exmode.nim
- src/moepkg/normalmode.nim
- src/moepkg/search.nim
- src/moepkg/visualmode.nim
- tests/teditorstatus.nim
Reverts fox0430/moe#1297
Close #1298
> Revert "Refactor edistorstatus.update"

- src/moepkg/exmode.nim
- tests/texmode.nim
> Not save the Ex command if it is the same command as last time (#1305)

- .github/workflows/actions.yaml
- README.md
- documents/configfile.md
- example/moerc.toml
- src/moepkg/configmode.nim
- src/moepkg/editor.nim
- src/moepkg/exmode.nim
- src/moepkg/settings.nim
- src/moepkg/visualmode.nim
- tests/tconfigmode.nim
- tests/teditor.nim
- tests/texmode.nim
- tests/tsettings.nim
- tests/tvisualmode.nim
> Clipboard: Add xsel support (#1311)

- src/moepkg/configmode.nim
> Configuration mode: Add support for change array settings

- example/moerc.toml
- src/moepkg/color.nim
- tests/tconfigmode.nim
> Change default color of parenTextBg (#1270)

- src/moepkg/build.nim
- src/moepkg/exmode.nim
> Delete TaintedString (#1322)

- documents/configfile.md
- example/moerc.toml
- src/moepkg/color.nim
- src/moepkg/configmode.nim
- src/moepkg/insertmode.nim
- src/moepkg/settings.nim
- tests/tconfigmode.nim
- tests/tinsertmode.nim
- tests/tsettings.nim
- Delete ```WorkSpace``` table
- Delete ```Notification.workspaceScreenNotify```
- Delete ```Notification.workspaceLogNotify```
- Delete ```Debug.WorkSpace``` table
- Delete ```Theme.workspaceBar```
- Delete ```Theme.workspaceBarBg```
> Delete settings for Workspace

- src/moepkg/bookmark.nim
- src/moepkg/editor.nim
- src/moepkg/insertmode.nim
- src/moepkg/movement.nim
- src/moepkg/normalmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/unicodeext.nim
- tests/teditor.nim
- tests/tinsertmode.nim
- tests/tmovement.nim
- tests/tnormalmode.nim
- Fix ```r``` command behavior
- Fix  ```~``` command behavior
- Fix  ```d{``` and ```d}``` commands behavior
- Fix ```Ctrl-x``` and ```Ctrl-a``` commands behavior
- Fix ```o``` and ```O``` command behavior
> Refactor and fix normalmode.nim and editor.nim

- documents/configfile.md
- src/moepkg/clipboard.nim
- src/moepkg/configmode.nim
- src/moepkg/settings.nim
- tests/tsettings.nim
> Clipboard: Add wl-clipboard support

- src/moepkg/color.nim
- src/moepkg/highlight.nim
- src/moepkg/syntax/highlite.nim
- src/moepkg/syntax/syntaxnim.nim
> nim callroute , route name , types and const name syntaxhighlight

- example/moerc.toml
- src/moe.nim
- src/moepkg/clipboard.nim
- src/moepkg/independentutils.nim
- src/moepkg/insertmode.nim
- src/moepkg/replacemode.nim
- src/moepkg/settings.nim
- tests/tconfigmode.nim
> Clipboard: Automatically set the clipboard tool on Linux

- src/moepkg/editor.nim
- src/moepkg/unicodeext.nim
- tests/teditor.nim
Enhance auto-indent for some languages (Nim, C, C++, C#, Java, JS, Yaml).
Close #874
> Enhance autoindent

- src/moepkg/editor.nim
- src/moepkg/normalmode.nim
- tests/teditor.nim
> Normal mode: Enable autoindent with "o" and "O" commands

- src/moe.nim
- src/moepkg/bufferstatus.nim
- src/moepkg/cmdlineoption.nim
- src/moepkg/editorstatus.nim
- src/moepkg/messages.nim
- src/moepkg/normalmode.nim
Add ```-R``` option (Readonly mode)
> Add Readonly mode

- src/moepkg/normalmode.nim
- src/moepkg/visualmode.nim
- tests/tvisualmode.nim
> Enable Visual (block) mode when Readonly mode

- tests/tnormalmode.nim
- tests/tvisualmode.nim
> Add tests for Readonly mode

- src/moepkg/editor.nim
It's a very little change but I couldn't wait for it
> Add '=' case to autoindent

- src/moepkg/editor.nim
I think it's better like this, but it's only my feeling
> Less-confusing parentheses

- moe.nimble
> Add `nimble debug`

- example/moerc.toml
- src/moepkg/settings.nim
- tests/tsettings.nim
> Improved performance of validation of configuration files

- moe.nimble
This reverts commit 602f338869e83d86d6c45a0545f98366c4fb7b07.
> Revert "Fix Nim version"
